version: "3.7"
services:
  breedbase:
    image: breedbase/breedbase:v0.92
    depends_on:
      - breedbase_db
    container_name: breedbase_web
    ports:
      - 8080:8080
    volumes:
      - type: bind
        source: ${HOME}/cxgn
        target: /home/production/cxgn
      - type: bind
        source: ${HOME}/cassava-devel.sgn.cornell.edu/sgn_local.conf
        target: /home/production/cxgn/sgn/sgn_local.conf
      - type: bind
        source: ${HOME}/public
        target: /home/production/public
  breedbase_db:
    image: breedbase/breedbase_pg12.4:v0.5
    container_name: breedbase_db
    environment:
        - TZ=America/New_York
#    ports:
#      - 5431:5432
    volumes:
      - type: bind
        source: /home/production/docker/pgdata
        target: /var/lib/postgresql/data
